project:
  type: website

website:
  title: "Garrett's Blog"
  page-footer:
    center:
      - icon: linkedin
        href: https://www.linkedin.com/in/garrettrmooney
      - icon: twitter
        href: https://www.twitter.com/garrettrmooney
      - icon: github
        href: https://www.github.com/garrettmooney
  twitter-card:
      creator: "@garrettrmooney"
      site: "@garrettrmooney"
      card-style: summary_large_image
  site-url: https://garrettmooney.github.io
  description: "A collection of blogs on machine learning and data science."
  repo-url: https://github.com/garrettmooney/garrettmooney.github.io
  repo-actions: [edit]
  repo-branch: master
  draft-mode: unlinked
  navbar:
    title: false
    background: dark
    pinned: true
    collapse: false
    left:
      - text: "Blog"
        href: index.qmd
        target: _blank
      - text: "Notes"
        href: notes/index.qmd
        target: _blank

    sidebar:
      - title: Notes
        pinned: false
        collapse-level: 1
        style: docked
        contents: notes/

format:
  html:
    reference-location: document
    code-copy: true
    code-overflow: wrap
    respect-user-color-scheme: true
    theme:
      dark: [cosmo, theme-new-dark.scss]
      light: [cosmo, theme-new.scss]
    css:
      - styles.css
    toc: true
