project:
  type: website

website:
  title: "Garrett's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/garrettmooney
      - icon: twitter
        href: https://twitter.com/garrettrmooney
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



